### ISSUE TITLE
S05E03一处翻译改进

### ISSUE THREAD

**Issue by qianbinbin** [N-Bourbaki/Rick-and-Morty-Chinese-Subtitles#11]
S05E03台词 no commitments 出现了两次，个人觉得翻译成“不准投入”比较恰当，“不能承诺”就怪怪的
另外能否把字幕上传到shooter.cn等网站，这样IINA播放器就可以在线查找，不用手动下载了

**Comment by smellyeddie** [comment]
您的建议我觉得有道理，会体现在最近的修改里，如果没有其他不便，我会把您的ID加在片头。其他网站和自动播放的问题因为我没用过相关设备不太了解，您方便提供更具体的说明其重要性的信息吗？因为多一个由我们上传的网站（而不是被转载）就意味着多维护一套账号和更新，我们倾向于除非十分必要尽量简化这类操作，也欢迎您入群讨论

**Comment by qianbinbin** [comment]
挂名啥的随意吧，我只改了一句话，有点尴尬hh
字幕老实说我也不太懂，IINA是mac上常用的播放器，有一个在线查找字幕功能，支持shooter.cn、opensubtitles.org和assrt.net，我用shooter.cn查到了一个srt字幕
但貌似shooter.cn很早就关闭了，所以很诡异，它的上传入口在哪……或许别的字幕组知道？
只是建议，仅供参考

**Comment by smellyeddie** [comment]
好，这样吧，群里应该懂的多，我交给他们决定（如果有热心人帮转就更好了），虽然我一个外行不能保证结果。挂名的事不必尴尬，放在GitHub的初衷就是众人拾柴火焰高，有一个贡献算一个贡献，挑错的话热闹一点才质量高。应该都说到位了那我就把issue关了哈，感谢。
