### ISSUE TITLE
S

### ISSUE THREAD

**Issue by maxshq** [N-Bourbaki/Rick-and-Morty-Chinese-Subtitles#12]
[Rick and Morty S05E05.txt](https://github.com/N-Bourbaki/Rick-and-Morty-Chinese-Subtitles/files/6838214/Rick.and.Morty.S05E05.txt)

**Comment by smellyeddie** [comment]
感谢您的热心，但是调过轴的版本我已经发到 SubHD 了，敬请关注。本 issue 将被关闭

**Comment by smellyeddie** [comment]
> [Rick and Morty S05E05.txt](https://github.com/N-Bourbaki/Rick-and-Morty-Chinese-Subtitles/files/6838214/Rick.and.Morty.S05E05.txt)

抱歉，刚在合并双语没想太多。欢迎进群，尽管目前有人提供官方字幕，不过如果您也能提供第一手字幕，我们这里来源多多益善~
