### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by xzf525** [N-Bourbaki/Rick-and-Morty-Chinese-Subtitles#13]
https://i.loli.net/2021/07/21/poT2ZIRPVEJ7aQL.png
https://i.loli.net/2021/07/21/kf9tlHvrWodZE6T.png

**Comment by smellyeddie** [comment]
如果您愿意发起PR，我很乐意merge（~~显得热闹~~）

**Comment by ToddPackerDMPC** [comment]
已修正，感谢！
