### ISSUE TITLE
字幕编辑问题

### ISSUE THREAD

**Issue by wyq977** [N-Bourbaki/Rick-and-Morty-Chinese-Subtitles#17]
hi 谢谢你们的整理翻译 很喜欢你们的ass格式 想把我的一些中英字幕合并一下

1. 想问下你们用的ass编辑软件是什么呀
2. ass格式
3. general workflow: 因为我编辑修改感觉很慢 虽然只是大部分的复制粘贴

**Comment by fjn308** [comment]
提前说一句可能会让您失望，合轴的真相其实主要还是大力出奇迹：剪切粘贴，当然到第五季最后两集前我考虑到这样连做两集得疯，我就写个了 ahk 脚本（见下条回复），让我提高了那么一丢丢的效率。

您应该也了解，合轴的障碍源于中英两条字幕轨之间的区别往往并非只有语言：比如时间轴对不上、断句对不上，以及漏译等等。这导致目前找不到一个完美的工具来完全自动化这一流程，特别是断句的修改目前只能靠人工。

可以想象，软件能做的无非就是以尽可能高的精度把一行中文和一行英文对上，然后人工把错的改一改、把根本不可能对上的拽一拽。软件之间的区别应该只在于为了对上这些行采用的思路以及处理异常的策略。具体的软件我就不做推荐了，因为我都没真正用过，它们应该很容易被找到。值得一提的是我们内部一位成员也写过相关的工具，后面他可能来回复一下。

所以……我说了好多但好像又啥也没说，再次抱歉。下面是几个问题的回答：

1，AegiSub、VSCode 和 NotePad++

2，我……没太看懂？

3，弄清楚 ass 文件规范中对自己有用的部分语法，确定自己心仪的样式并写下它，从此以它为模版以后基本天天套用就行了。把字幕文件当文本当代码看待，并注重它的美观性，拒绝那些把字幕当字幕看待的工具生成的闹眼睛代码（比如每行重复出现的大括号某某样式）。充分利用习惯的文本编辑器的功能（比如正则表达式、AegiSub 平移拉伸时间轴和限定在字幕文本内搜索替换的功能、VSCode 的不闹眼睛、NotePad++ 处理空白字符的功能以及它的插件们……），见机行事积累一系列属于自己的奇技艺淫巧。几次处理下来，就会总结出适合自己的规范流程。比如对于我们来说，同一季中的字幕特点差不多，会采用同一套流程，而换季了字幕特点变了，流程也变了。流程大抵都是前一半搜索替换后一半大力出奇迹。

**Comment by smellyeddie** [comment]
提前说一句可能会让您失望，合轴的真相其实主要还是大力出奇迹：剪切粘贴，当然到第五季最后两集前我考虑到这样连做两集得疯，我就写个了 ahk 脚本（见下条回复），让我提高了那么一丢丢的效率。

您应该也了解，合轴的障碍源于中英两条字幕轨之间的区别往往并非只有语言：比如时间轴对不上、断句对不上，以及漏译等等。这导致目前找不到一个完美的工具来完全自动化这一流程，特别是断句的修改目前只能靠人工。

可以想象，软件能做的无非就是以尽可能高的精度把一行中文和一行英文对上，然后人工把错的改一改、把根本不可能对上的拽一拽。软件之间的区别应该只在于为了对上这些行采用的思路以及处理异常的策略。具体的软件我就不做推荐了，因为我都没真正用过，它们应该很容易被找到。值得一提的是我们内部一位成员也写过相关的工具，后面他可能来回复一下。

所以……我说了好多但好像又啥也没说，再次抱歉。下面是几个问题的回答：

1，AegiSub、VSCode 和 NotePad++

2，我……没太看懂？

3，弄清楚 ass 文件规范中对自己有用的部分语法，确定自己心仪的样式并写下它，从此以它为模版以后基本天天套用就行了。把字幕文件当文本当代码看待，并注重它的美观性，拒绝那些把字幕当字幕看待的工具生成的闹眼睛代码（比如每行重复出现的大括号某某样式）。充分利用习惯的文本编辑器的功能（比如正则表达式、AegiSub 平移拉伸时间轴和限定在字幕文本内搜索替换的功能、VSCode 的不闹眼睛、NotePad++ 处理空白字符的功能以及它的插件们……），见机行事积累一系列属于自己的奇技淫巧。几次处理下来，就会总结出适合自己的规范流程。比如对于我们来说，同一季中的字幕特点差不多，会采用同一套流程，而换季了字幕特点变了，流程也变了。不过流程大抵都是前一半搜索替换后一半大力出奇迹（好吧，我读了一遍感觉自己其实啥也没说）。

**Comment by smellyeddie** [comment]
```
#SingleInstance Force

ini = true

^+a::
If (%ini%)
{
    ini = false
    Send {LButton}
    Send {End}
    Send +{Home}
    Send ^x
}
Else
{
    ini = true
    Send {LButton}
    Send {End}
    Send ^v
}
Return

^+z::
ExitApp
```
以上是一个简易的 ahk 脚本示例，配合有快捷键的鼠标使用。脚本使得按下 `ctrl+shift+a` 的时候剪切掉鼠标所在行，再按一下粘贴到鼠标所在行的末尾；按下 `ctrl+shift+z` 时重新运行脚本。这样把鼠标上的某个按键设置成 `ctrl+shift+a` 时，就可以用 vscode 并置两个文档然后点一下左面点一下右面点一下左面点一下右面……发现需要改断句了改一改然后点一下左面点一下右面……如果再把某个按键设置成 `ctrl+shift+z`，点乱了时按一下它就可以重置脚本让它下一次迈左脚。

这个愚蠢的脚本适合于处理 srt 格式或者把 ass 格式文件做简单的处理后使用。它还可以更复杂一点点，比如只剪切 `,,0,0,0,,` 后的内容，比如粘贴到 `\N{\ren}` 之前，等等。

至于这种破烂脚本和现行的破烂工具们比到底谁更好用一点……就看个人喜好了。

**Comment by wyq977** [comment]
谢啦谢啦

我也是最近在重新整理老剧《70年代秀》的时候发现网上的字幕可以说是基本没有了
[That-70s-Show-Chinese-Subtitiles](https://github.com/wyq977/That-70s-Show-Chinese-Subtitiles)

一开始用OCR和一些软件从老的视频（伊甸园）200*年的rmvb视频。。。 发现效率极低而且还是需要人工校对。

最近准备试下直接用Google translate粗略翻译一下然后在直接校对，感觉工作量很大，可能搞搞就没力气弄了:(。

人气比较少的剧像《70年代秀》资源很少，当时的翻译也很一般。其实都已经看过了，觉得整理一下分享出去比较好。

我开始也是直接用vscode编辑，毕竟srt ass都只是纯文本，准备试用[Jubler](https://www.jubler.org/)，macos下面选择也不多。。。

可能后面会把`chi.srt`和`eng.srt`合并ass 想到这里的ass格式、字体都很舒服就来咨询一下。


> ass格式

这我主要就是问下ass的字体，大小颜色、位置什么的，因为这些srt好像都没有。还有就是开头info的添加了吧。 其实就是想找到类似于best practive with srt/ass或者format guide for srt/ass 有点像编程语言的format guide之类吧

比如说有的时候会加一些解释 好像ass可以挑字体位置，不知道你们的习惯是怎么样的。还有一些小问题，比如中文符合和"？" 和英文符号"?"，地名人名的翻译与否之类的。一直都是字幕的消费者，才发现产出也这么折磨人。

比如下面这幅图，如果要加一些注释，应该加到哪里呢

![Screen Shot 2021-09-29 at 12 15 15 AM](https://user-images.githubusercontent.com/27303600/135173563-651f1eaf-a70e-4347-a469-fa8f70c2d561.png)
另外如果多人对话，同时加上中英双语的位置摆放问题 如下图：

谢谢耐心回答啦！
![Screen Shot 2021-09-29 at 12 18 24 AM](https://user-images.githubusercontent.com/27303600/135173570-8fc9c7d4-e312-4cfa-8dec-ced578fa6b8f.png)

**Comment by wyq977** [comment]
看到不少帖子求资源，也有不少人尝试自己制作字幕，发现大部分都不了了之了，很是感慨。

[贴吧有人双语制作，太监了](https://tieba.baidu.com/p/4242565554)

**Comment by SubtitleMaster** [comment]
可以试试这个程序 https://github.com/SubtitleMaster/srt-2-bilingual-ass 将两个语言的srt字幕合并，优先采用中文的时间轴，可以处理少量时间轴不同的情形，否则直接保留中文丢弃英文。如果中英文本来一一对应效果完全可用。

**Comment by smellyeddie** [comment]
> 可能搞搞就没力气弄了:(

想想就难，不过加油~

---

> 问下ass的字体，大小颜色、位置什么的，还有就是开头 info 的添加

您可以参考我们的样式，引用如下：
```
[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: zh,微软雅黑,70,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,20,1
Style: en,Comic Sans MS,40,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
Style: top,微软雅黑,35,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,8,10,10,10,1
Style: git,Comic Sans MS,35,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,8,10,10,10,1
```

如样式名字所描述的，`zh` 是中文字幕，`en` 是英文字幕，`top` 是顶端字幕，`git` 是 GItHub 仓库链接使用的样式。

在字体选取和注释、特效样式的问题上我们曾经有过很多讨论，但到最后的决定就是从简，也就是用最简单的设计让效果达到 80 分。80 分以后的提升会让制作精力陡升，代码上也不美观，还是更多地专注在译文上比较好。

比如字体，其实除了美观我们主要考虑的是兼容性问题，所以用的微软雅黑和 Comic Sans MS，这两款字体在很大比例的计算机上都是被预装的（当然 Linux 上可能没有，不过人家都用 Linux 了这种问题也无需我们操心了），可以最大程度保证字幕不会 duang 一下就显示成宋体了这种。

再比如特效（画面中需要翻译的文本）和注释（译文中需要解释的内容）我们一律从简，没太大必要的就不写，写了也一律用 top 这种没什么存在感的样式。每个字幕风格都有它的受众，我们假想的受众有一定的英文水平和联想能力，其实也在于我们的成员有点反感“狗皮膏药”式的注释。注释多到影响观感它们就适得其反，说得不够会有点莫名其妙，这个问题见仁见智，但我们偏向后者。还有就是一些来源信息可以写在最开头 `[Script Info]` 的 `Title` 字段：
```
[Script Info]
Title: S05E03 by Nicolas Bourbaki
```

以及一些鸡肋内容可以用行首加 `;` 的方式注释掉。至于开头 info，您也可以参考我们的字幕文件：
```
[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.25,0:00:04.75,top,,0,0,0,,本字幕由Nicolas Bourbaki调轴及合并双语 首先发布于SubHD
Dialogue: 0,0:00:05.25,0:00:09.75,top,,0,0,0,,转载请注明来源保留信息 开源分享的互联网精神你有我有大家有
Dialogue: 0,0:00:10.25,0:00:14.75,top,,0,0,0,,Nicolas Bourbaki不建议也不对任何利用本字幕生成的视频负责
Dialogue: 0,0:00:15.25,0:00:19.75,top,,0,0,0,,第五季至此季终 八集官译两集原创 各位下季见 祝大家生活快乐
Dialogue: 0,0:00:20.25,0:00:24.75,top,,0,0,0,,[特别感谢] 每周在第一时间提供第一手HBO官方字幕的热心群友
Dialogue: 0,0:00:25.25,0:00:29.75,top,,0,0,0,,欢迎大家到我们的仓库协助改错：{\rgit}https://github.com/N-Bourbaki/Rick-and-Morty-Chinese-Subtitles
```

我们的风格是五秒钟一句话，两句话之间空半秒。小小的字体不妨碍观看，也就是尽可能地削弱它的存在感。

---

> 字体位置

基于上面“从简”的风格，我们基本上在设定好样式以后就不手动修改具体某行字的位置了，除非有特殊情况，比如 S05E10 的：
```
Dialogue: 0,0:00:06.93,0:00:09.48,zh,,0,0,0,,{\c&H74e4ed&}第13章：听天由命\N\N\N\N\N\N\N\N\N\N\N\N\N\N\N\N\N\N\N\N\N\N\N
```

是的，就这么糊弄人，我加了一堆换行来把字幕位置推上去。以及这里 `{\c&H74e4ed&}` 的用法，事实上我们整季只用了三四处，都是为了配合英文硬字幕的颜色而原来的白色太违和才被迫用的，也就是能不折腾就不折腾。

---

> 一些小问题，比如中文符号"？" 和英文符号"?"，地名人名的翻译与否之类的。

我们自己翻译时，会替换掉除了双引号、书名号、歌词星号（注意，书名号和双引号都是通常的中文符号，我们认为无需瘦身成单引号和大于小于号）之外的所有标点符号，按需替换成空格（跟微信打字似的）。这里说的是中文，英文我们最多在有两个说话人时用横杠分开两个人的话，其他的就不动了。

这个剧集语速快对白长，太多标点符号会让观众看得很累。但是，在使用官方译本时我们保留了其中的标点符号，一方面就是懒，再说别人的翻译我们原则上只改错误，另一方面是官方的翻译言简意赅并不长，所以标点倒让字幕饱满点，不然不剩啥了。

至于名们，我们的做法是有通常翻译的或有明确含义的就译出，否则保留原文。事实上您提到的点在我们的内部手册上都有规定，这个手册以前挂在这个仓库来着，后来考虑到其中有些东西不适合对外就删了，暂时不提供了。对于您的情况，我想如果有长期志愿者加入（我们在这个角度说其实挺幸运的），这时你们应该也需要写这样一个文档。在此之前如果合作只涉及处理零散的 pr 的话（也别抱太大幻想，见我们的 issue、pr 数），自己按照自己的规则统一风格其实比给每个人讲清规范来得快一些（写那种文档挺累的）。

上面说了这些，下面的两个图的问题就可以简单回答了。加注释的话我们最多用 `top` 样式简单翻译一下，最有可能的是不翻译，这集是官方翻译的，所以转盘处的注释我是从官方译本复制粘贴然后加上 `top` 样式的。至于多人说话的写法，也是从简，在我们的字幕中随便复制一段：
```
Dialogue: 0,0:04:20.47,0:04:22.21,zh,,0,0,0,,-本来就不是俄罗斯 Jerry -本姑娘现在心碎成渣\N{\ren}-It's not Russia, Jerry. -My heart is broken,
```

注意这里的英文是用逗号结尾的，意味着我们只是把它生硬地在标点符号处断开，除非有问题（打字错误、没空格、没加横杠之类的，前提也是注意到了，不会特意查）不去管它。这么做的另外一个原因是我们总觉得在遥远的将来会用蓝光字幕洗版英文部分，所以它到底会被换掉，差不多就行了。

---

> 有点像编程语言的 format guide 之类

这种东西网上确实有的，我当时（谷歌）搜的是“ass 规范”，您可以看一下，如果看到非常非常非常官方来源的记得回来贴下链接~

---

P.S. 上面评论的 @SubtitleMaster 就是我前面提到的成员啦

**Comment by smellyeddie** [comment]
> 按下 `ctrl+shift+z` 时重新运行脚本

这部分相关的我写错了，我最开始确实是那样写的，后来改成了上面代码中的样子。这里 `ctrl+shift+z` 是退出脚本，因为我另设置了一个快捷键来运行脚本，配合开头的 `#SingleInstance Force` 达到重新运行的作用。不重要，小儿科没啥可说的了=。=

**Comment by wyq977** [comment]
谢啦 我用 aegisub 和那个 python script 搞了两集

[s01e01](https://github.com/wyq977/That-70s-Show-Chinese-Subtitiles/blob/main/s01/chi/That-70s-Show_s01e01.chi%26eng.ass) and [s01e02](https://github.com/wyq977/That-70s-Show-Chinese-Subtitiles/blob/main/s01/chi/That-70s-Show_s01e02.chi%26eng.ass)

所以你们是全部不用中文逗号了吗 「，」全部都替换成俩空格了嘛

![Screen Shot 2021-09-29 at 3 15 32 PM](https://user-images.githubusercontent.com/27303600/135277264-a0ca540a-833b-46c2-9d05-fa1391e6ac46.png)
![Screen Shot 2021-09-29 at 3 15 58 PM](https://user-images.githubusercontent.com/27303600/135277283-31a2f6d5-d3a2-492c-9973-49b86d71bed1.png)
![Screen Shot 2021-09-29 at 3 16 05 PM](https://user-images.githubusercontent.com/27303600/135277302-85cac906-de99-44a9-b9cb-258d4f613802.png)


PS.
能问下你们为什么选择 [SubHD](https://subhd.com)，因为我一直都用[字幕库](http://zmk.pw/)

**Comment by smellyeddie** [comment]
啊对，我在 repo 的 readme 结尾艾特您和之前认识的另一位同好 @Gatorix 了，祝愿能做下去和做好。

**Comment by wyq977** [comment]
谢了谢了

祝好！
