### ISSUE TITLE
请问S05E00会做中文字幕吗？

### ISSUE THREAD

**Issue by ZHAODayou** [N-Bourbaki/Rick-and-Morty-Chinese-Subtitles#18]
10月上旬出的Rick.and.Morty.S05E00.The.Great.Yokai.Battle.of.Akihabara，请问会做字幕吗？谢谢！

**Comment by smellyeddie** [comment]
抱歉回晚了：应该不会做这个了，一是我们基本上只做（过）正规集数，二来，更主要的，看起来大家都比较忙，群目前基本是冬眠的状态。感谢您关注我们。

**Comment by ZHAODayou** [comment]
谢谢回复，感谢你们之前的付出！
