### ISSUE TITLE
S05E03翻译讨论

### ISSUE THREAD

**Issue by diertian** [N-Bourbaki/Rick-and-Morty-Chinese-Subtitles#19]
发现几处翻译存在问题，记录一下，一起讨论一下吧。

> Dialogue: 0,0:00:06.48,0:00:08.57,zh,,0,0,0,,我好喜欢这种新衬衫才有的味道啊\N{\ren}Ahh, I love that new T-shirt smell.
> Dialogue: 0,0:00:08.61,0:00:10.35,zh,,0,0,0,,小妞儿们要是看见我们穿了\N{\ren}Chicks are gonna be all up in our biz
> Dialogue: 0,0:00:10.40,0:00:12.05,zh,,0,0,0,,这身儿Rick and Morty定制衬衫 就该把持不住了\N{\ren}when they see us wearing these Rick and Morty custom tees.
> Dialogue: 0,0:00:12.09,0:00:13.57,zh,,0,0,0,,我敢说这能卖得出去\N{\ren}I bet we could sell these.
> Dialogue: 0,0:00:13.62,0:00:14.88,zh,,0,0,0,,那当然啊 我太他妈喜欢周边了\N{\ren}Hells yeah. I fuckin' love merch!【翻译有误】营销merchandising的缩写

> Dialogue: 0,0:00:40.30,0:00:43.04,zh,,0,0,0,,你的酸雨 真是好酸呢\N{\ren}Your acid rain is an acid pain...
> Dialogue: 0,0:00:43.08,0:00:44.91,zh,,0,0,0,,酸到令人作呕呀 柴油黄鼠狼\N{\ren}in the butt, Diesel Weasel!
> Dialogue: 0,0:00:44.95,0:00:46.30,zh,,0,0,0,,-唉呀呀 -哇哦\N{\ren}-Yikes. -Wow.
> Dialogue: 0,0:00:46.35,0:00:47.91,zh,,0,0,0,,那个话都说不利索的小妞是谁\N{\ren}Who's the chick in need of a dialogue pass?【翻译有误】那个说话不中听的小妞是谁（为什么需要dialogue pass?用ass比用butt更押韵？）

> Dialogue: 0,0:05:17.53,0:05:18.97,zh,,0,0,0,,呃 那天\N{\ren}S-So it was, uh, great hanging --
> Dialogue: 0,0:05:19.01,0:05:20.58,zh,,0,0,0,,那天和你很开心啊\N{\ren}hanging out the other day.
> Dialogue: 0,0:05:20.62,0:05:22.49,zh,,0,0,0,,我有点儿 我觉得 咱俩\N{\ren}I-I was getting kind of a -- I mean I-I got kind of
> Dialogue: 0,0:05:22.53,0:05:23.67,zh,,0,0,0,,咱俩进展还不错\N{\ren}a p-positive vibe.【翻译有误】当时我感觉有些良好
> Dialogue: 0,0:05:23.71,0:05:25.41,zh,,0,0,0,,那太好了 搞得我好紧张\N{\ren}Oh, good. I was putting one out.【翻译有误】put yourself out 当时我可是费尽心力
> Dialogue: 0,0:05:25.45,0:05:26.54,zh,,0,0,0,,我很喜欢你\N{\ren}I-I really like you.

> Dialogue: 0,0:21:56.48,0:21:59.18,zh,,0,0,0,,早\N{\ren}'Morning.
> Dialogue: 0,0:21:59.23,0:22:00.36,zh,,0,0,0,,今天时间好慢 哈\N{\ren}Slow day, huh?【翻译有误】生意冷清
> Dialogue: 0,0:22:00.40,0:22:01.66,zh,,0,0,0,,是\N{\ren}Yep.
> Dialogue: 0,0:22:01.71,0:22:03.97,zh,,0,0,0,,可能是因为人人都认为\N{\ren}Probably because everybody thought
> Dialogue: 0,0:22:04.01,0:22:08.84,zh,,0,0,0,,这世界今天不会 嗯 还在这\N{\ren}the world wouldn't be, you know, like, here today.

**Comment by se9fault** [comment]
谢谢你的认真与意见！
1. merch 是 merchandise，周边商品的缩写。比如“Rick and Morty定制衬衫”就是 Rick and Morty 的周边商品。Google 一下 merch 就能看到很多这种用法
2. dialogue pass 是编剧术语，指 a "pass" of rewriting only the "dialogue" of the screenplay，也就是“订正剧本时，通读全剧本，但只检查所有的对话”。这里是指 Planetina 的台词拗口，需要编剧给她改改台词，所以译作“说话不利索”
3. vibe 一般指“微妙气氛”，而不是“自我感觉”。因为 Morty 在说两人约会的事情，所以这里的 getting a posivite vibe 是省略了 "from you"。下文 I was putting one out 的 one 指的就是 this positive vibe
4. slow day 从来没见过有“生意冷清”的意思，这个您是如何考虑的呢

**Comment by diertian** [comment]
感谢回复！一起讨论，共同进步啦！

1. 原来这里的译文“周边”是“周边商品”的缩写呀，看来是我中文不好，所以一直纳闷怎么翻译成“周边”。
2. 这里之所以需要修改对话，是因为Planetina 的台词拗口吗？我听她吐字清楚，还以为是不押韵造成的呢。
3. 对的，是“我对你感觉良好”。不过“put out”在这里应该不是“紧张”的意思，我理解的是“我费尽心力让你对我有好感”。
4. 这里是劫后次日，儿子回到父亲的店里工作，店里的生意冷清/slow。
