### ISSUE TITLE
S05E04 错字修正

### ISSUE THREAD

**Issue by FleTimePro** [N-Bourbaki/Rick-and-Morty-Chinese-Subtitles#20]
>Dialogue: 0,0:15:21.83,0:15:24.63,zh,,0,0,0,,－他的经纪人还得用补蝶网… －安静\N{\ren}-His agent had to catch him with a butterfly net. -Silence!

这句是否应为

>Dialogue: 0,0:15:21.83,0:15:24.63,zh,,0,0,0,,－他的经纪人还得用捕蝶网… －安静\N{\ren}-His agent had to catch him with a butterfly net. -Silence!

补 --> 捕

**Comment by smellyeddie** [comment]
已修正，非常感谢！
